/*
 * This source file was generated by the Gradle 'init' task
 */
package ee.reneroost

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
    // val greeting: String? = null
}

fun main() {
    println(App().greeting)
}
